// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MenstrualCycleCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("last_period_date")]
        public DateTimeOffset LastPeriodDate { get; set; }

        [JsonProperty("cycle_length")]
        public long CycleLength { get; set; }

        [JsonProperty("period_length")]
        public long PeriodLength { get; set; }

        [JsonProperty("cycles_calculated")]
        public long CyclesCalculated { get; set; }

        [JsonProperty("cycles")]
        public Cycle[] Cycles { get; set; }

        [JsonProperty("current_status")]
        public CurrentStatus CurrentStatus { get; set; }

        [JsonProperty("averages")]
        public Averages Averages { get; set; }

        [JsonProperty("disclaimer")]
        public string Disclaimer { get; set; }
    }

    public partial class Averages
    {
        [JsonProperty("cycle_length")]
        public long CycleLength { get; set; }

        [JsonProperty("period_duration")]
        public long PeriodDuration { get; set; }

        [JsonProperty("days_between_periods")]
        public long DaysBetweenPeriods { get; set; }
    }

    public partial class CurrentStatus
    {
        [JsonProperty("phase")]
        public string Phase { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("next_period")]
        public object NextPeriod { get; set; }

        [JsonProperty("days_until_next_period")]
        public object DaysUntilNextPeriod { get; set; }
    }

    public partial class Cycle
    {
        [JsonProperty("cycle_number")]
        public long CycleNumber { get; set; }

        [JsonProperty("period")]
        public FertileWindow Period { get; set; }

        [JsonProperty("ovulation")]
        public CycleOvulation Ovulation { get; set; }

        [JsonProperty("fertile_window")]
        public FertileWindow FertileWindow { get; set; }

        [JsonProperty("pms_phase")]
        public PmsPhase PmsPhase { get; set; }

        [JsonProperty("cycle_phases")]
        public CyclePhases CyclePhases { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("days_until")]
        public object DaysUntil { get; set; }

        [JsonProperty("days_ago")]
        public long DaysAgo { get; set; }
    }

    public partial class CyclePhases
    {
        [JsonProperty("menstrual")]
        public Follicular Menstrual { get; set; }

        [JsonProperty("follicular")]
        public Follicular Follicular { get; set; }

        [JsonProperty("ovulation")]
        public CyclePhasesOvulation Ovulation { get; set; }

        [JsonProperty("luteal")]
        public Follicular Luteal { get; set; }
    }

    public partial class Follicular
    {
        [JsonProperty("start")]
        public DateTimeOffset Start { get; set; }

        [JsonProperty("end")]
        public DateTimeOffset End { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class CyclePhasesOvulation
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class FertileWindow
    {
        [JsonProperty("start_date")]
        public DateTimeOffset StartDate { get; set; }

        [JsonProperty("end_date")]
        public DateTimeOffset EndDate { get; set; }

        [JsonProperty("duration_days")]
        public long DurationDays { get; set; }
    }

    public partial class CycleOvulation
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("day_of_cycle")]
        public long DayOfCycle { get; set; }
    }

    public partial class PmsPhase
    {
        [JsonProperty("start_date")]
        public DateTimeOffset StartDate { get; set; }

        [JsonProperty("end_date")]
        public DateTimeOffset EndDate { get; set; }
    }
}
